# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10c26d601602b870e85d93d8699d6c82f1f2016ddc0eeaaa30608b05bcd2b2ec3268f2da2f8db407a13ff2cd8ad82ce746dfc74f4c3cbcafc18d896ba984d8c9

test:
  secret_key_base: 0442eb1dfc5713d354aaa4eee5860435c8cd7ddefe3f9534dbcf42f48c1ca1db09a9b005c7a6e91e8b0227bf2cae1837f9ac9e28bf7871628c064fb46828946d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
