development:
  adapter: postgresql
  encoding: unicode
  database: novelist_development
  pool: 5
  username: Eric
  password:

test: &TEST
  adapter: postgresql
  encoding: unicode
  database: novelist_test
  pool: 5
  username: Eric
  password: