# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a3129c37b8f6f190cdaf14cb31b4fd9d23d01d4b73aaa33af27f2c7f1a31d101ea22038e37e85ee5b1b7a01496ae60e4cb062b1265d988b53c893045dd15e10

test:
  secret_key_base: 547bc5a29bcb9cab866de443124b9d2936fc8d4e0fd0679d20e06e5678c59cc36031ea7e17c174d524c4e2f510037990db406755ec54aee6f8638cc548f1ed4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
